var lang = new Map();

lang.set("af", "Afrikaans");
lang.set("sq", "Albanian");
lang.set("am", "Amharic");
lang.set("ar", "Arabic");
lang.set("hy", "Armenian");
lang.set("az", "Azeerbaijani");
lang.set("eu", "Basque");
lang.set("be", "Belarusian");
lang.set("bn", "Bengali");
lang.set("bs", "Bosnian");
lang.set("bg", "Bulgarian");
lang.set("ca", "Catalan");
lang.set("ceb", "Cebuano");
lang.set("zh-CN", "Chinese (Simplified)");
lang.set("zh-TW", "Chinese (Traditional)");
lang.set("co", "Corsican");
lang.set("hr", "Croatian");
lang.set("cs", "Czech");
lang.set("da", "Danish");
lang.set("nl", "Dutch");
lang.set("en", "English");
lang.set("eo", "Esperanto");
lang.set("et", "Estonian");
lang.set("fi", "Finnish");
lang.set("fr", "French");
lang.set("fy", "Frisian");
lang.set("gl", "Galician");
lang.set("ka", "Georgian");
lang.set("de", "German");
lang.set("el", "Greek");
lang.set("gu", "Gujarati");
lang.set("ht", "Haitin Creole");
lang.set("ha", "Hausa");
lang.set("haw", "Hawaiian");
lang.set("iw", "Hebrew");
lang.set("hi", "Hindi");
lang.set("hmn", "Hmong");
lang.set("hu", "Hungarian");
lang.set("is", "Icelandic");
lang.set("ig", "Igbo");
lang.set("id", "Indonesian");
lang.set("ga", "Irish");
lang.set("it", "Italian");
lang.set("ja", "Japanese");
lang.set("jw", "Javanese");
lang.set("kn", "Kannada");
lang.set("kk", "Kazakh");
lang.set("km", "Khmer");
lang.set("ko", "Korean");
lang.set("ku", "Kurdish");
lang.set("ky", "Kyrgyz");
lang.set("lo", "Lao");
lang.set("la", "Latin");
lang.set("lv", "Latvian");
lang.set("lt", "Lithuanian");
lang.set("lb", "Luxembourgish");
lang.set("mk", "Macedonian");
lang.set("mg", "Malagasy");
lang.set("ms", "Malay");
lang.set("ml", "Malayalam");
lang.set("mt", "Maltese");
lang.set("mi", "Maori");
lang.set("mr", "Marathi");
lang.set("mn", "Mongolian");
lang.set("my", "Myanmar (Burmese)");
lang.set("ne", "Nepali");
lang.set("no", "Norwegian");
lang.set("ny", "Basque");
lang.set("ny", "Nyanja (Chichewa)");
lang.set("ps", "Pashto");
lang.set("fa", "Persian");
lang.set("pl", "Polish");
lang.set("pt", "Portuguese");
lang.set("pa", "Punjabi");
lang.set("ro", "Romanian");
lang.set("ru", "Russian");
lang.set("sm", "Samoan");
lang.set("gd", "Scots Gaelic");
lang.set("sr", "Serbian");
lang.set("st", "Sesotho");
lang.set("sn", "Shona");
lang.set("sd", "Sindhi");
lang.set("si", "Sinhala");
lang.set("sk", "Slovak");
lang.set("sl", "Slovenian");
lang.set("so", "Somali");
lang.set("es", "Spanish");
lang.set("su", "Sundanese");
lang.set("sw", "Swahili");
lang.set("sv", "Swedish");
lang.set("tl", "Tagalog (Filipino)");
lang.set("tg", "Tajik");
lang.set("ta", "Tamil");
lang.set("te", "Telugu");
lang.set("th", "Thai");
lang.set("tr", "Turkish");
lang.set("uk", "Ukrainian");
lang.set("ur", "Urdu");
lang.set("uz", "Uzbek");
lang.set("vi", "Vietnamese");
lang.set("cy", "Welsh");
lang.set("xh", "Xhosa");
lang.set("yi", "Yiddish");
lang.set("yo", "Yoruba");
lang.set("zu", "Zulu");

exports.languageMap = lang;
